version: 2.1

executors:
    node:
        working_directory: ~/workdir
        docker:
            - image: cimg/node:16.14

jobs:
    build:
        executor: node
        steps:
            - checkout
            - run: sudo npm install --global npm@8.3.0

            - run: npm ci
            - run: npm run ts
            - run: npm run lint
            - run: npm run build:generate-types
            - run: npm test
            - run: npm run unused-exports

            - persist_to_workspace:
                  root: .
                  paths:
                      - .

    deploy:
        executor: node
        parameters:
            env:
                type: enum
                enum:
                    [
                        'terraform',
                        'nordiv-dev',
                        'dev',
                        'staging',
                        'beta',
                        'prod',
                    ]
            project:
                type: enum
                enum:
                    [
                        'ent-selvbet-terraform-dev',
                        'ent-client-nordic-dev',
                        'entur-dev',
                        'entur-staging',
                        'entur-beta',
                        'entur-prod',
                    ]
            function:
                type: string
                default: ''
        docker:
            - image: google/cloud-sdk
        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: Set gcloud Auth
                  command: |
                      echo $GCLOUD_SERVICE_KEY_<< parameters.env >> | gcloud auth activate-service-account --key-file=-
            - run:
                  name: Set gcloud project
                  command: |
                      gcloud --quiet config set project entur-<< parameters.env >>
            - run:
                  name: Upload type defs to GCP bucket
                  command: |
                      gsutil cp typeDeclarations.tar.gz "gs://<< parameters.project >>-bff-search-types/"
            - run:
                  name: Deploy to Google App Engine
                  command: |
                      gcloud app deploy ./app-<< parameters.env >>.yaml cron.yaml --quiet --verbosity=info

workflows:
    build-and-test:
        jobs:
            - build
    deployment:
        jobs:
            - build

            - approval-dev:
                  type: approval
                  requires:
                      - build

            - deploy:
                  env: 'dev'
                  name: dev
                  project: 'entur-dev'
                  requires:
                      - approval-dev

            - approval-staging:
                  type: approval
                  requires:
                      - build

            - deploy:
                  env: 'staging'
                  name: staging
                  project: 'entur-staging'
                  requires:
                      - approval-staging

            - approval-beta:
                  type: approval
                  requires:
                      - build

            - deploy:
                  env: 'beta'
                  name: beta
                  project: 'entur-beta'
                  requires:
                      - approval-beta

            - approval-prod:
                  type: approval
                  requires:
                      - build

            - deploy:
                  env: 'prod'
                  name: prod
                  project: 'entur-prod'
                  requires:
                      - approval-prod

            - approval-terraform:
                  type: approval
                  requires:
                      - build

            - deploy:
                  env: 'terraform'
                  name: terraform
                  project: 'ent-selvbet-terraform-dev'
                  requires:
                      - approval-terraform

            - approval-nordic-dev:
                  type: approval
                  requires:
                      - build

            - deploy:
                  env: 'nordic-dev'
                  name: nordic-dev
                  project: 'ent-client-nordic-dev'
                  requires:
                      - approval-nordic-dev
