version: 2.1

executors:
    node:
        working_directory: ~/workdir
        docker:
            - image: cimg/node:16.14

jobs:
    build:
        executor: node
        steps:
            - checkout
            - run: sudo npm install --global npm@8.3.0

            - run: npm ci
            - run: npm run ts
            - run: npm run lint

            - run: npm test
            - run: npm run unused-exports

    # deploy:
    #     executor: node
    #     parameters:
    #         env:
    #             type: enum
    #             enum: ['dev', 'staging', 'beta', 'prod']
    #         function:
    #             type: string
    #             default: ''
    #     steps:
    #         - checkout
    #         - run: sudo npm install --global npm@8.3.0

    #         - run: npm ci
    #         - run:
    #               name: Create service account file for dev
    #               command: echo $FIREBASE_DEPLOY_CREDENTIALS_DEV > /tmp/serviceaccount.dev.json
    #         - run:
    #               name: Create service account file for staging
    #               command: echo $FIREBASE_DEPLOY_CREDENTIALS_STAGING > /tmp/serviceaccount.staging.json
    #         - run:
    #               name: Create service account file for beta
    #               command: echo $FIREBASE_DEPLOY_CREDENTIALS_BETA > /tmp/serviceaccount.beta.json
    #         - run:
    #               name: Create service account file for prod
    #               command: echo $FIREBASE_DEPLOY_CREDENTIALS_PROD > /tmp/serviceaccount.prod.json
    #         - run:
    #               name: Deploy << parameters.function >> to << parameters.env >>
    #               command: GOOGLE_APPLICATION_CREDENTIALS="/tmp/serviceaccount.<< parameters.env >>.json" npm run deploy << parameters.env >> << parameters.function >>

workflows:
    build-and-test:
        jobs:
            - build
