version: 2.1

executors:
    node:
        working_directory: ~/workdir
        docker:
            - image: cimg/node:16.14

jobs:
    build:
        executor: node
        steps:
            - checkout
            - run: sudo npm install --global npm@8.3.0

            - run: npm ci
            - run: npm run ts
            - run: npm run lint

            - run: npm test
            - run: npm run unused-exports

    deploy:
        executor: node
        parameters:
            env:
                type: enum
                enum: ['dev', 'staging', 'beta', 'prod']
            function:
                type: string
                default: ''
        docker:
            - image: google/cloud-sdk
        steps:
            - checkout
            - run: sudo npm install --global npm@8.3.0

            - run: npm ci
            - run: |
                  echo $GCLOUD_SERVICE_KEY_<< parameters.env >> | gcloud auth activate-service-account --key-file=-
                  gcloud --quiet config set project entur-<< parameters.env >>
                  gcloud app deploy app-<< parameters.env >>.yaml

workflows:
    build-and-test:
        jobs:
            - build
    deployment:
        jobs:
            - build

            - approval-dev:
                  type: approval
                  requires:
                      - build

            - deploy:
                  env: 'dev'
                  name: dev
                  requires:
                      - approval-dev
