export const ENVIRONMENT: string
export const TRANSIT_HOST: string
export const NON_TRANSIT_HOST: string
export const TRANSIT_HOST_OTP2: string
export const NON_TRANSIT_HOST_OTP2: string
export const REDIS_HOST: string
export const REDIS_PORT: string
export const PARTNER_AUDIENCE: string
export const PARTNER_HOST: string
