name: Deploy bff-search

on:
    workflow_dispatch:
        inputs:
            deployToDev:
                type: boolean
                description: dev
                default: false
            deployToStaging:
                type: boolean
                description: staging
                default: true
            deployToBeta:
                type: boolean
                description: beta
                default: false
            deployToProd:
                type: boolean
                description: prod
                default: false
            deployToInt:
                type: boolean
                description: int
                default: false
    workflow_call:
        inputs:
            environment:
                type: string
                description: Deployment environment
                required: true

jobs:
    calculate-matrix:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{steps.calculate-deploy-matrix.outputs.result}}
        steps:
            - uses: actions/checkout@v4
            - name: Calculate parameters
              uses: actions/github-script@v7
              id: calculate-deploy-matrix
              with:
                  script: |
                      const { calculateEnvironment } = await import('${{github.workspace}}/.github/workflows/utils.mjs');
                      const inputs = ${{toJSON(inputs)}}
                      const environment = calculateEnvironment(inputs)

                      return { asset: [inputs.asset], environment }

    deploy-bff-search:
        name: Deploy bff-search to ${{matrix.environment.gcp}}
        runs-on: ubuntu-latest
        needs: calculate-matrix
        environment: ${{matrix.environment.gha}}
        permissions:
            contents: read
            pull-requests: write
            id-token: write
        strategy:
            fail-fast: false
            matrix: ${{ fromJSON(needs.calculate-matrix.outputs.matrix) }}
        steps:
            - uses: actions/checkout@v4

            - name: Build and test
              uses: ./.github/actions/build-and-test

            - name: Populate Google application credentials
              uses: google-github-actions/auth@v2
              with:
                  workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
                  service_account: ${{ vars.SERVICE_ACCOUNT }}
                  create_credentials_file: true

#            - name: Set gcloud Auth
#              run: echo $FIREBASE_DEPLOY_CREDENTIALS | gcloud auth activate-service-account --key-file=-
#              env:
#                  FIREBASE_DEPLOY_CREDENTIALS: ${{secrets.FIREBASE_DEPLOY_CREDENTIALS}}

            - name: Set gcloud project
              run: gcloud --quiet config set project ${{vars.GCP_PROJECT}}

            - name: Upload type defs to GCP bucket
              run: gcloud storage cp typeDeclarations.tar.gz "gs://${{vars.GCP_PROJECT}}-search-types/"

            - name: Deploy to Google App Engine
              run: gcloud app deploy ./app-${{matrix.environment.gcp}}.yaml cron.yaml --quiet --verbosity=info

            - name: Send Slack message
              run: ./scripts/slack.sh ./app-${{matrix.environment.gcp}}
              env:
                  ENTUR_DEPLOY_SLACK_WEBHOOK: ${{secrets.ENTUR_DEPLOY_SLACK_WEBHOOK}}
