name: Nightly Deploy

on:
    schedule: # Times are in UTC
        #        - cron: '0 5 * * 1-5'
        - cron: '15 15 * * 1-5'

jobs:
    deploy-bff:
        uses: ./.github/workflows/deploy.yml
        secrets: inherit
        with:
            environment: '["dev", "int", "staging", "beta"]'
